# Dependencies
markdown:         kramdown
# highlighter:      pygments
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            gLidar
tagline:          'An atmospheric convection project'
email:            duro24@gmail.com
description:      'An atmospheric convection research project using data from sailplanes, paragliding and LIDARs.'
baseurl:          /
url:              http://glidar-project.github.io/

disqus:
  shortname:      'gLidar'

author:
  name:           'Juraj Palenik'
  url:            https://vis.uib.no/team/palenik/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/glidar-project.github.io

exclude:
  - vendor
